### PR TITLE
Open day menu on hover

### PR DESCRIPTION
**Pull request by niranjan94**
The day menu on the schedule page opens on hover. As suggested by @mariobehling in issue #8 .

### CODE REVIEW

**Comment by niranjan94** [comment]
Can be previewed @ https://niranjan94.github.io/2016.opentechsummit.net/programm/

**Comment by niranjan94** [comment]
@mariobehling this commit is required for the day menu to open on hover. You have already merged the scraper side of it (OpenTechSummit/open-event-scraper#4).

**Comment by mariobehling** [comment]
@niranjan94 Please help to resolve the merge conflict here.

**Comment by niranjan94** [comment]
Will do it

**Comment by niranjan94** [comment]
@mariobehling Conflicts have been resolved.

**Pull request merged**
