### PR TITLE
Fix day menu hover on mobile and hiding of day on desktop

### LINKED ISSUE #31: Submenu partly hidden in mobile/small screen view
Please see screenshot below.
screenshot from 2016-04-28 12 25 37

### PR DESCRIPTION
**Pull request by niranjan94**
This PR fixes the issue of the day menu in mobile devices. It also corrects the menu such that the Day is not hidden in desktop. 

Resolves #31 .

**Preview:** https://niranjan94.github.io/2016.opentechsummit.net/programm/

### CODE REVIEW

**Comment by mariobehling** [comment]
@niranjan94 Please keep the open on scroll over and the changes of color on scroll over the menu items.

**Comment by niranjan94** [comment]
@mariobehling this does not remove the open on scroll over feature in desktops. The colors have also been untouched.

**Comment by mariobehling** [comment]
still merging it. we can progress step by step. Thank you!

**Comment by mariobehling** [comment]
@niranjan94 You need to implement this in the scraper as well, right?

**Comment by niranjan94** [comment]
@mariobehling Not required. It's handled entirely by `css/schedule.css`.

**Comment by shivamMg** [comment]
@mariobehling The scraper generates only the `index.html`, and all the other static assets are in the 2016.ots.net repo.

**Pull request merged**
