### PR TITLE
Change the anchor symbol to a link symbol for links

### PR DESCRIPTION
**Pull request by niranjan94**
This changes `fa-anchor` to `fa-link` as suggested by @mariobehling . Resolves issue #9 .

**Screenshot:**
capture

### CODE REVIEW

**Comment by mariobehling** [comment]
Looks nice, but I think, if you don't change the scraper output, this change will be overwritten at the next update. We are generating the page through a script.

**Comment by mariobehling** [comment]
https://github.com/OpenTechSummit/open-event-scraper

**Comment by niranjan94** [comment]
Yea. I noticed that. Working on it.

**Comment by niranjan94** [comment]
Okay. This PR is now invalid as the changes have been done in the scrapper. 
New pull request at OpenTechSummit/open-event-scraper#4 .

**Pull request closed without merging**
