### PR TITLE
footer style added

### PR DESCRIPTION
**Pull request by aayusharora**

### CODE REVIEW

**Comment by mariobehling** [comment]
@aayusharora Actually, I do not understand why you are adding this here. We need the scraper to generate everything. So, please contribute to the scraper. We just keep the issues here for legacy reasons.

**Comment by aayusharora** [comment]
@mariobehling  , we don't maintain css folders in scraper till now  , hence it can not be done there .
Moreover in my previous issue  https://github.com/OpenTechSummit/2016.opentechsummit.net/issues/59 ,
I have asked to add css folder and other files required in the scraper  for making schedule folder self-sufficient so that  by running build.sh in scraper , they are added to 2016.opentechsummit automatically by git.
@championswimmer  , whats your view point ?

**Comment by aayusharora** [comment]
@mariobehling 
**1) How we are doing now ?**
   -CSS folder is in 2016.opentechsummit and not in scraper , CSS can not be changed in scraper until it is added there , we have to update build.sh also .
**2)  Approach that should be followed :**
      - Add CSS folder to scraper => Generate it to 2016.opentechsummit repo in programm folder by running  build.sh  in scraper .
       - run self.js to make Schedule folder in 2016.opentechsummit repo that is self-sufficient .

**Comment by mariobehling** [comment]
@aayusharora Ok, yes. Imagine the repository is empty and nothing inside (I have repeated this on different occasions). Everything needs to be added into the scraper - css, js - and generated into an empty repository. I am really not sure, how to make it clearer:
A) You have an empty repository
B) You generate a schedule through JSON files
C) The final web page holds all information including css -> There is no other interaction required by the user.

**Pull request closed without merging**
